name: Download Torrent (file index)

on:
  workflow_dispatch:
    inputs:
      FILE_INDEX:
        description: 'FILE_INDEX'
        required: true
      MAGNET:
        description: 'MAGNET'
        required: true
      ARCHIVE_NAME:
        description: 'ARCHIVE_NAME'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download Torrent
        run: |
          aria2c --select-file="${{ github.event.inputs.FILE_INDEX }}" --seed-time=0 "${{ github.event.inputs.MAGNET }}"
          rm *.aria2

      - name: Zip Downloaded Torrent
        run: zip -r "${{ github.event.inputs.ARCHIVE_NAME }}.zip" *

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: "${{ github.event.inputs.ARCHIVE_NAME }}.zip"
